### ISSUE TITLE
Image library optimisation

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#40]
The image library is already a bit chaotic. Images are sprinkled all over the place so it's hard to know which image is used where.  some images are too small and other are way too big - the biggest one is 100 times the smallest one.   see image below.  

<img width="1680" alt="UploadsLibraryChaos" src="https://user-images.githubusercontent.com/13426392/73144065-80c85800-40f5-11ea-894d-63e3584c5c62.png">

We need to:

* refactor the folder structure so that there is an image folder for each static page
* add sub-folders for each experience under the relevant experience type folder. 
* remove duplicate images and move them to the right folder/subfolder
* resize all oversize images to a maximum for a good on-screen display of something like 2000 x 1200 or so?
* establish a convention for thumbnail images - eg the ones on the calendar panel.  maybe 720 x 500 or so?

happy to modify how this works a bit to suit cloud canon - so long as we achieve the intent of a better organised image library where it's easy to know which image is on which page etc..

**Comment by webilhan** [comment]
Image reorganization has been done. 

For now, we have the following structure:
For all static pages like (About the Yacht, Ocean Races, Cruising....) images will be loaded in
`uploads/static-pages/{page-title}`
Image will be resize to cover the size 1920x1020, width 1920px and height less 1020px or height 1020px and width less then 1920px

For experiences, we have the following structure:
**Experience thumbnail and content images**
![Experience thumbnail](https://user-images.githubusercontent.com/1095354/73304514-16143b00-4221-11ea-8311-5ee77d29b72d.png) will be in 
`uploads/{experience-type}/{experience-title}`
Image will be resized to cover the size 960x510, so width 960px and height less 510px or height 510px and width less then 960px. 
Content image sizes as for static pages above.

### Gallery images:
**Thumbnails:**
![Thumbnails](https://user-images.githubusercontent.com/1095354/73304436-ebc27d80-4220-11ea-9e9c-b6c63fc913fb.png): `uploads/{experience-type}/{experience-title}/gallery-thumbnails` 
Cover size 120x120px

**Images:**
![Images](https://user-images.githubusercontent.com/1095354/73304464-faa93000-4220-11ea-9c4b-00f2ffee8782.png) 
`uploads/{experience-type}/{experience-title}/gallery-images`
Image will be resize to cover the size 1920x1020, so width 1920px and height less 1020px, or height 1020px and width less then 1920px
_They have to be in separate folders because in other case cloudcannon will not resize it after upload if it will be the same image._

For crew members, all images will be in folder: `uploads/crew/` and resized to contain 186x233px

**Comment by onthebreeze** [comment]
ok tested and seems fine.  thank you.  closing the issue
