### ISSUE TITLE
Map error 

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#63]
Hi Ilya,

I am not sure if this is because of my connection or if there is any issue with the website but could you check if there is any Map Loading Errors? I have received this error: https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

Many thanks,
Jess

**Comment by webilhan** [comment]
@JessiJess @onthebreeze It is because google requires to enable billing account for google maps. See [docs](https://developers.google.com/maps/gmp-get-started). We need to enable it and update Google maps key with new one. It can be updated at [settings](https://app.cloudcannon.com/17137/editor#/site/35794/explore/_data:/explore/_data/settings.yaml)

**Comment by JessiJess** [comment]
Hi @webilhan , thanks for looking into this issue. Is is something that we do or that you do?

**Comment by onthebreeze** [comment]
I checked the google console and, even though there is a current and active payment method (swanningaround card), the billing account was closed.  I think i've reopened it and all is ok.  the API key was unchanged.  maps seems to work on the swanningaround.com website.

@JessiJess could you check that things are working as you expect and close this ticket if ok
