### ISSUE TITLE
change the color of the background on home page

### ISSUE THREAD

**Issue by benjaminroulant** [gs-gs/swanningaround#64]
fff

**Comment by webilhan** [comment]
@benjaminroulant Homepage has a white background and small overlay, that's why it looks different.
I think removing the overlay and make the background fully white will looks not very nice in some cases, because menu icon and icons in the right top corner could be not really visible. See example https://prnt.sc/xx64bh
@JessiJess ^^

**Comment by JessiJess** [comment]
Hi Ilya, sorry it was just a test to show Ben how an issue is generated. I will close it now.
